package iwb.domain.db;

// Generated May 18, 2007 3:50:53 AM by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Immutable;

/**
 * WFileAttachment generated by hbm2java
 */

@Entity
@Immutable
@Table(name="w5_file_attachment",schema="iwb")
public class W5FileAttachment implements java.io.Serializable {

	private int tableId;

	private String tablePk;

	private Short tabOrder;

	private String systemFileName;
	
	private String orijinalFileName;

	private int fileSize;	

	private String fileComment;

	private Integer fileTypeId;
	
	private int uploadUserId;
	
	private int customizationId;	

	private int fileAttachmentId;
	
	private short activeFlag;
	
	public W5FileAttachment() {
	}
	
    @SequenceGenerator(name="sex_file_attachment",sequenceName="iwb.seq_file_attachment",allocationSize=1)
	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="sex_file_attachment")
	@Column(name="file_attachment_id")
	public int getFileAttachmentId() {
		return fileAttachmentId;
	}

	public void setFileAttachmentId(int fileAttachmentId) {
		this.fileAttachmentId = fileAttachmentId;
	}

	@Column(name="table_id")
	public int getTableId() {
		return tableId;
	}
	
	public void setTableId(int tableId) {
		this.tableId = tableId;
	}

	@Column(name="table_pk") 
	public String getTablePk() {
		return tablePk;
	}

	public void setTablePk(String tablePk) {
		this.tablePk = tablePk;
	}

	@Column(name="tab_order") 
	public Short getTabOrder() {
		return tabOrder;
	}

	public void setTabOrder(Short tabOrder) {
		this.tabOrder = tabOrder;
	}

	@Column(name="system_file_name") 
	public String getSystemFileName() {
		return systemFileName;
	}
	
	public void setSystemFileName(String systemFileName) {
		this.systemFileName = systemFileName;
	}

	@Column(name="original_file_name") 
	public String getOrijinalFileName() {
		return orijinalFileName;
	}

	public void setOrijinalFileName(String orijinalFileName) {
		this.orijinalFileName = orijinalFileName;
	}
	
	@Column(name="file_size") 
	public int getFileSize() {
		return fileSize;
	}
	
	public void setFileSize(int fileSize) {
		this.fileSize = fileSize;
	}

	@Column(name="file_comment") 
	public String getFileComment() {
		return fileComment;
	}

	public void setFileComment(String fileComment) {
		this.fileComment = fileComment;
	}

	@Column(name="file_type_id") 
	public Integer getFileTypeId() {
		return fileTypeId;
	}

	public void setFileTypeId(Integer fileTypeId) {
		this.fileTypeId = fileTypeId;
	}

	@Column(name="upload_user_id") 
	public int getUploadUserId() {
		return uploadUserId;
	}

	public void setUploadUserId(int uploadUserId) {
		this.uploadUserId = uploadUserId;
	}

	@Id
	@Column(name="customization_id") 
	public int getCustomizationId() {
		return customizationId;
	}
	
	public void setCustomizationId(int customizationId) {
		this.customizationId = customizationId;
	}

	@Column(name="active_flag") 
	public short getActiveFlag() {
		return activeFlag;
	}
	
	public void setActiveFlag(short activeFlag) {
		this.activeFlag = activeFlag;
	}
}
