package iwb.domain.db;

// Generated Feb 15, 2007 7:51:41 PM by Hibernate Tools 3.2.0.b9

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Immutable;

import iwb.util.GenericUtil;

/**
 * WTableField generated by hbm2java
 */
@Entity
@Immutable
@Table(name="w5_table_field_calculated",schema="iwb")
public class W5TableFieldCalculated implements java.io.Serializable, W5Base {

	private int tableFieldCalculatedId;
	private int tableFieldId;

	private int tableId;
	private int relatedTableId;

	private String dsc;
	private String sqlCode;
	
	private short tabOrder;
	private short fieldTip;
	public W5TableFieldCalculated() {
	}
	
	@Id
	@Column(name="table_field_calculated_id")
	public int getTableFieldCalculatedId() {
		return tableFieldCalculatedId;
	}

	public void setTableFieldCalculatedId(int tableFieldCalculatedId) {
		this.tableFieldCalculatedId = tableFieldCalculatedId;
	}

	@Column(name="related_table_id")
	public int getRelatedTableId() {
		return relatedTableId;
	}

	public void setRelatedTableId(int relatedTableId) {
		this.relatedTableId = relatedTableId;
	}

	@Column(name="sql_code")
	public String getSqlCode() {
		return sqlCode;
	}

	public void setSqlCode(String sqlCode) {
		this.sqlCode = sqlCode;
	}
	@Column(name="table_field_id")
	public int getTableFieldId() {
		return this.tableFieldId;
	}

	public void setTableFieldId(int tableFieldId) {
		this.tableFieldId = tableFieldId;
	}

	@Column(name="table_id")
	public int getTableId() {
		return this.tableId;
	}

	public void setTableId(int tableId) {
		this.tableId = tableId;
	}


	@Column(name="tab_order")
	public short getTabOrder() {
		return this.tabOrder;
	}



	public void setTabOrder(short tabOrder) {
		this.tabOrder = tabOrder;
	}
	

	@Column(name="dsc")
	public String getDsc() {
		return dsc;
	}

	public void setDsc(String dsc) {
		this.dsc = dsc;
	}
	
	@Column(name="field_tip")
	public short getFieldTip() {
		return fieldTip;
	}

	public void setFieldTip(short fieldTip) {
		this.fieldTip = fieldTip;
	}

	@Transient
	public boolean safeEquals(W5Base q){
		if(q==null)return false;
		W5TableFieldCalculated t = (W5TableFieldCalculated)q;
		return 	
			this.tableFieldCalculatedId==t.tableFieldCalculatedId &&
			this.tableFieldId==t.tableFieldId &&
			this.fieldTip==t.fieldTip &&
			this.tableId==t.tableId &&
			this.relatedTableId==t.relatedTableId &&
			GenericUtil.safeEquals(this.dsc, t.dsc) &&
			GenericUtil.safeEquals(this.sqlCode, t.sqlCode) &&
			this.tabOrder==t.tabOrder;
	}
	private String projectUuid;
	@Id
	@Column(name="project_uuid")
	public String getProjectUuid() {
		return projectUuid;
	}

	public void setProjectUuid(String projectUuid) {
		this.projectUuid = projectUuid;
	}

}
